@baseUrl = http://localhost:3000
# 액세스 토큰을 입력하세요
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWt3OXh1YzAwMDAwZ2RmaGNpeGZ0YmVvIiwiYWNjb3VudElkIjoiY21rdzl4dWMwMDAwMWdkZmg2Z2R0bzc0cyIsInBsYXRmb3JtIjoiV0VCIiwiaWF0IjoxNzY5NjgzMjY1LCJleHAiOjE3Njk2ODQxNjUsImF1ZCI6ImFwaSIsImlzcyI6ImVhc3ktY2xpcCJ9.Q7uRlx4qjdQ2PfbU6HbZxR3osq5R9T7F8qTNagBp8D4
# 테스트에 사용할 폴더 ID를 입력하세요
@folderId = cmkwdetqk0007gd3wbph6k575


### 텍스트/컬러 클립 생성 (multipart)
# 포스트맨으로 하쇼


### 이미지 클립 생성 (multipart, file 우선)
# 포스트맨으로 하쇼

### 클립 단건 조회
@clipId = 
GET {{baseUrl}}/clips/{{clipId}}
Authorization: Bearer {{accessToken}}

### 클립 목록 조회 (폴더 기준, cursor는 초기 빈 값)
GET {{baseUrl}}/clips?folderId={{folderId}}&cursor=&type=ALL
Authorization: Bearer {{accessToken}}

### 클립 목록 조회 (favorite)
GET {{baseUrl}}/clips?favorite=true&cursor=&type=ALL
Authorization: Bearer {{accessToken}}

### 클립 목록 조회 (recent)
GET {{baseUrl}}/clips?recent=true&cursor=&type=ALL
Authorization: Bearer {{accessToken}}

### 클립 목록 조회 (타입 필터 + 검색)
GET {{baseUrl}}/clips?folderId={{folderId}}&cursor=&type=IMAGE&q=키워드
Authorization: Bearer {{accessToken}}

### 클립 수정 (text 변경, multipart)
PATCH {{baseUrl}}/clips/{{clipId}}
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=clipBoundary

--clipBoundary
Content-Disposition: form-data; name="text"

수정된 클립
--clipBoundary--

### 클립 삭제 (소프트 삭제)
DELETE {{baseUrl}}/clips/{{clipId}}
Authorization: Bearer {{accessToken}}
