@baseUrl = http://localhost:3000
# 액세스 토큰을 입력하세요
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWt1M2puN2kwMDAwZ2R0NGR1dXZ1Nmk1IiwiYWNjb3VudElkIjoiY21rdTNqbjdpMDAwMWdkdDRpZ3I4ZDR2cCIsInBsYXRmb3JtIjoiV0VCIiwiaWF0IjoxNzY5MzY3MzI0LCJleHAiOjE3NjkzNjgyMjQsImF1ZCI6ImFwaSIsImlzcyI6ImVhc3ktY2xpcCJ9.h6SAftbKM9JPS58O1LOg727K6qpzYkKon7NucJu6jmo

### 폴더 A 생성
# @name createFolderA
POST {{baseUrl}}/folders
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Folder A"
}

### 폴더 B 생성
# @name createFolderB
POST {{baseUrl}}/folders
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Folder B"
}

### 폴더 C 생성
# @name createFolderC
POST {{baseUrl}}/folders
Authorization: Bearer {{accessToken}}
Content-Type: application/json  

{
  "name": "Folder C"
}

### 폴더 목록 조회
GET {{baseUrl}}/folders
Authorization: Bearer {{accessToken}}

### 폴더 A 상세 조회
@folderAId = {{createFolderA.response.body.$.id}}
GET {{baseUrl}}/folders/{{folderAId}}
Authorization: Bearer {{accessToken}}

### 폴더 A 클립 목록 조회 (첫 페이지)
# 폴더에 클립이 존재해야 응답이 채워집니다.
# @name getFolderAClipsFirst
GET {{baseUrl}}/folders/{{folderAId}}/clips?limit=20
Authorization: Bearer {{accessToken}}

### 폴더 A 클립 목록 조회 (다음 페이지)
# nextCursor가 null이면 다음 페이지가 없다는 의미입니다.
@folderAClipsNextCursor = {{getFolderAClipsFirst.response.body.$.nextCursor}}
GET {{baseUrl}}/folders/{{folderAId}}/clips?limit=20&cursor={{folderAClipsNextCursor}}
Authorization: Bearer {{accessToken}}

### 폴더 A 수정
PATCH {{baseUrl}}/folders/{{folderAId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Folder A (Updated)"
}

### 타겟 폴더 앞으로 순서 변경 (맨앞으로 이동의 경우)
PATCH {{baseUrl}}/folders/reorder
Authorization: Bearer {{accessToken}}
Content-Type: application/json  

{
  "targetId": "cmkwa0t1g0007gd78o6fm88k1",
  "beforeId": "cmkwa0w6n000dgd78ktzdsl7b"
}


### 폴더 A를 폴더 C 뒤로 순서 변경
@folderBId = {{createFolderB.response.body.$.id}}
PATCH {{baseUrl}}/folders/reorder
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "targetId": "cmkwa0t1g0007gd78o6fm88k1",
  "afterId": "cmkwa1lh1000jgd78txdvzccm"
}

### 폴더 B 삭제(소프트 삭제)
DELETE {{baseUrl}}/folders/{{folderBId}}
Authorization: Bearer {{accessToken}}

### 삭제 후 폴더 목록 조회
GET {{baseUrl}}/folders
Authorization: Bearer {{accessToken}}
